#!/usr/bin/python3

import sys
from surrounded_regions import Solution
board = [["X", "X", "X", "X", "X"], ["X", "X", "X", "O", "X"], [
    "X", "X", "O", "X", "X"], ["O", "X", "X", "X", "O"], ["X", "X", "X", "X", "X"]]
print(Solution().solve(board))
board = [["O", "O"], ["O", "O"]]
print(Solution().solve(board))
